osx_image: xcode7.3
language: objective-c
script:
- open -b com.apple.iphonesimulator
- xcodebuild -scheme Switch -workspace Switch.xcworkspace -sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' build test | xcpretty
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'Switch'
